name: StellarMining
version: ${project.version}
main: net.stellar.mining.StellarMining
api-version: 1.16
authors: [ Stellar, Chubbyduck1 ]
description: A custom made advanced mining plugin
softdepend: [ WorldEdit, WorldGuard ]