Loading-Settings:
    Debug-Mode: true

Command-Settings:
    Command-Permission: "stellarmining.admin" #Command usage permission
    Command: "stellarmining" #Main command to use
    Aliases: #Other possible commands to use
        - "stellarminings"
        - "mining"
        - "minings"
        - "sm"