Loading-Settings:
    Debug-Mode: true

Command-Settings:
    Command-Permission: "cloudmining.admin" #Command usage permission
    Command: "cloudmining" #Main command to use
    Aliases: #Other possible commands to use
        - "cloudminings"
        - "mining"
        - "minings"
        - "cm"